name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./backend
      
    - name: Run tests
      run: |
        python -m pytest test_main.py -v
      working-directory: ./backend

  frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend
      
    - name: Run ESLint
      run: npm run lint
      working-directory: ./frontend
      
    - name: Run tests
      run: npm run test:run
      working-directory: ./frontend
      
    - name: Build project
      run: npm run build
      working-directory: ./frontend
